CREATE DATABASE wildlife_tracker ;

\c wildlife_tracker ;

CREATE TABLE animal(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animalName VARCHAR,
    age VARCHAR,
    animalType VARCHAR,
    health VARCHAR,
    id INT,
    createdBy VARCHAR,
    createdDate DATETIME,
);

CREATE TABLE sightings (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animalId INT,
    endangeredAnimal VARCHAR,
    rangerName VARCHAR,
    location VARCHAR,
    date DATETIME,
);


\dt
SELECT * FROM animals;
SELECT * FROM sightings;

CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;
\c wildlife_tracker_test;
