CREATE DATABASE animal;

\c hero;

CREATE TABLE animal(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heroName VARCHAR,
    heroAge INT,
    heroPower VARCHAR,
    heroWeakness VARCHAR,
    squadId INT,
    avatarUrl VARCHAR
);

CREATE TABLE sightings (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    squadName VARCHAR,
    squadCause VARCHAR,
    maxSize INT,
    squadFull BOOLEAN
);

CREATE DATABASE animal_test WITH TEMPLATE animal;
